/**
 * "Aperiodic Sets" family: the two golden rhombohedra, the 3D Penrose
 * pair (the Ammann–Kramer tiling of the icosahedral quasicrystal).
 * Each fills space on its own, periodically (any rhombohedron does), so
 * they are not a Space-Filling Pair; what is special is that together
 * they can also fill space with no repeat at all. (Face-to-face attaching
 * alone doesn't force that: in 3D it takes extra matching rules, or the
 * cut-and-project construction Rhombiverse's 6D world uses.)
 *
 * Built from three of the icosahedron's six 5-fold axes, each scaled to
 * the edge of this registry's RHOMBIC_TRIACONTAHEDRON (catalan.ts, edge
 * 1/phi at circumradius 1) -- not rescaled per shape, so their golden
 * rhombus faces are literally the triacontahedron's own and
 * facesCongruent() lets them attach to it and to each other (see
 * rd-relatives/index.ts for why a per-shape rescale would break that).
 *   prolate: axes pairwise at +1/sqrt5 (apex angles 63.435 deg)
 *   oblate:  axes pairwise at -1/sqrt5 (apex angles 116.565 deg)
 * Volumes are in the golden ratio. Each face lists its ACUTE corner
 * first, wound outward (the vertex-0 role computeFaceAttach relies on).
 * Generated by the same construction as Rhombiverse's
 * quasicrystal.js golden rhombohedra; checked in
 * scripts/verify-aperiodic-sets.ts.
 *
 * Known builds (assemblyNaming.ts): 2 prolate + 2 oblate = the Bilinski
 * dodecahedron, 5 + 5 = the rhombic icosahedron, 10 + 10 = the rhombic
 * triacontahedron.
 */
import { type PolyhedronSpec } from './core.js';
export declare const APERIODIC_ADDITIONS: Record<string, PolyhedronSpec>;
export declare const APERIODIC_ADDITION_IDS: string[];
/** The family holds two separate pairs, each a set of partners. */
export declare const APERIODIC_PAIRS: [string, string][];
