/**
 * Composite-Seed RCP investigation, Stage 6 — Question B ("What
 * geometric structure, if any, is generated by the complete RD-derived
 * mirror system?", hypothesis.md §11-§12).
 *
 * A DELIBERATE, DOCUMENTED INTERPRETIVE CHOICE (see
 * docs/composite-seed-rcp/reflectionGroup.md for the full reasoning):
 * hypothesis.md §12 Step 1-2 literally describe lifting a SPECIFIC
 * aggregate's own exposed facets into 4D via the RCP map -- but that
 * lift needs a theta (embedding-depth angle) the way each of the 4
 * ALREADY-VERIFIED regular seeds has one (tetrahedron/cube/octahedron/
 * dodecahedron, radialProjection.ts's own FOUR_D_SHAPE_PARAMS), and a
 * composite aggregate has no such theta -- inventing one here would be
 * exactly the kind of "silently re-derived from memory" the
 * investigation plan's own verification caveat warns against.
 *
 * This file instead answers the MORE FAITHFUL reading of hypothesis.md
 * §11's own question ("the complete RD-derived mirror system", stated
 * as an intrinsic property of the RD cell, not of any one aggregate):
 * the RD's own 12 facet-normal directions (Delta_RD), used as mirror
 * PLANES through the origin in 3D. This sidesteps the open-ended
 * "orbit growth to unknown depth" problem the investigation plan's own
 * Stage 6 acceptance criterion warns about: any group generated by a
 * FINITE set of reflections through the origin in R^3 with RATIONAL
 * (here: <110>-type) normals is a subgroup of a KNOWN finite point
 * group (order <= 48, the full octahedral group O_h) -- it is
 * mathematically guaranteed to close after boundedly many steps, not
 * an open question of "how deep is deep enough."
 */
import type { Vec3 } from '../core.js';
export type Mat3 = [[number, number, number], [number, number, number], [number, number, number]];
/** I - 2mm^T for a unit normal m -- the standard 3D reflection matrix, same convention as radialProjection.ts's own reflectionMatrix (just one dimension down). */
export declare function reflectionMatrix3(m: Vec3): Mat3;
export declare function matMul3(a: Mat3, b: Mat3): Mat3;
export declare function matVec3(a: Mat3, v: Vec3): Vec3;
/**
 * Deduplicated distinct mirror PLANES from DELTA_RD's 12 directions --
 * v and -v define the SAME reflection matrix (I-2mm^T is identical for
 * m and -m, since the outer product mm^T doesn't change sign), so 12
 * directions collapse to exactly 6 distinct generators. Checked, not
 * assumed: reflectionMatrix3(v) and reflectionMatrix3(-v) are compared
 * directly in the verify script.
 */
export declare function distinctRdMirrorNormals(): Vec3[];
/**
 * Step 1+2 (this file's own interpretation, see header): the generating
 * reflection matrices themselves -- one per distinct RD mirror normal.
 */
export declare function rdGeneratingReflections(): Mat3[];
/**
 * Step 6 analogue + closure: BFS group closure starting from the
 * identity, repeatedly multiplying every known element by every
 * generator, until no new element appears. GUARANTEED to terminate
 * (see file header) -- capped at `maxOrder` purely as a defensive
 * sanity bound (a bug producing an actually-infinite result would hit
 * this and should be reported as a bug, not silently truncated as
 * "finite").
 */
export interface GroupClosureResult {
  order: number;
  elements: Mat3[];
  /** True iff closure completed before hitting maxOrder -- false would mean either a real infinite group (shouldn't happen per the file header's own guarantee) or a bug. */
  closed: boolean;
}
export declare function closeGroup(generators: Mat3[], maxOrder?: number): GroupClosureResult;
/**
 * Step 7 analogue: orbit of a GENERIC point (no special symmetry of its
 * own -- irrational-ish coordinates chosen so it isn't accidentally
 * fixed by any nontrivial group element) under the closed group. For a
 * genuinely generic point, orbit size == group order (trivial
 * stabilizer) -- checked directly rather than assumed, since a
 * non-generic point could have a smaller orbit.
 */
export declare function orbitOfPoint(elements: Mat3[], p: Vec3): Vec3[];
export interface PairwiseAngle {
  i: number;
  j: number;
  cosAlpha: number;
  alphaDeg: number;
  /** pi/alpha rounded, if within tolerance of an integer -- the Coxeter m_ij candidate. */
  m?: number;
}
export declare function pairwiseAngles(normals: Vec3[]): PairwiseAngle[];
/** G_ij = -cos(pi/m_ij) for Coxeter-compatible pairs (1 on the diagonal), else the DIRECTLY MEASURED -cos(alpha_ij) -- hypothesis.md §12 Step 5's own instruction to produce both the idealized and the measured matrix; here unified into one matrix that prefers the idealized value only where compatibility was actually confirmed. */
export declare function gramMatrix(normals: Vec3[], angles: PairwiseAngle[]): number[][];
/** Symmetric eigenvalues via the Jacobi eigenvalue algorithm -- small fixed matrices (n<=6 here), no external linear-algebra dependency needed. */
export declare function symmetricEigenvalues(matrix: number[][], iterations?: number): number[];
