// The request pathway (stage 3 of DICTO's KRP plan): an environment asks for an object by its ID
// and gets it regenerated, with its description, instead of keeping its own copy. Stage 4 adds a
// session cache: never stored, never the authority, always equal to a fresh regeneration.
import { parseObjectId, KRP_VERSION } from './vocabulary.js';
import { RECORDS, describe, facesOf } from './identity/index.js';

/** Every generator the core can answer for. */
export const GENERATORS = Object.keys(RECORDS);

const CACHE_SIZE = 200;
const cache = new Map(); // id -> answer, oldest first
const deepFreeze = (o) => { if (o && typeof o === 'object' && !Object.isFrozen(o)) { Object.freeze(o); for (const v of Object.values(o)) deepFreeze(v); } return o; };

/**
 * The object an ID names: { description, faces, cached } (faces in the generator's own units;
 * read-only). An ID made by another core version is refused, since this core cannot promise to
 * regenerate it exactly, unless { anyVersion: true }: then it is regenerated by this core and the
 * answer says which version made the ID (madeWith). { fresh: true } skips the cache.
 */
export function request(id, { anyVersion = false, fresh = false } = {}) {
  const { generator, version, params } = parseObjectId(id);
  if (version !== KRP_VERSION && !anyVersion) throw new Error(`'${id}' was made by krp-core ${version}; this is krp-core ${KRP_VERSION}`);
  if (!RECORDS[generator]) throw new Error(`krp-core has no generator '${generator}'`);
  const key = `${generator}?${JSON.stringify(Object.entries(params).sort(([a], [b]) => (a < b ? -1 : 1)))}`;
  let answer = fresh ? undefined : cache.get(key);
  const cached = !!answer;
  if (cached) { cache.delete(key); cache.set(key, answer); } // most recently used last
  else {
    answer = deepFreeze({ description: describe(generator, params), faces: facesOf(generator, params) });
    if (!fresh) { cache.set(key, answer); if (cache.size > CACHE_SIZE) cache.delete(cache.keys().next().value); }
  }
  return { ...answer, cached, ...(version !== KRP_VERSION ? { madeWith: version } : {}) };
}

/** Empty the session cache (tests; nothing else needs it). */
export function clearCache() { cache.clear(); }
